# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-13 18:06
from __future__ import unicode_literals

import bbconnlab.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Diangosis Name')),
                ('ext_code', models.CharField(max_length=30, verbose_name='External code')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Last modified')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
            ],
            options={
                'verbose_name': 'Diagnosis',
                'verbose_name_plural': 'Diagnosis',
            },
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Doctor Name')),
                ('ext_code', models.CharField(max_length=30, verbose_name='External code')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Last modified')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
        ),
        migrations.CreateModel(
            name='Genders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Gender Name')),
                ('ext_code', models.CharField(max_length=30, verbose_name='External code')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Last modified')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
            ],
            options={
                'verbose_name': 'Gender',
                'verbose_name_plural': 'Genders',
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Insurence Name')),
                ('ext_code', models.CharField(max_length=30, verbose_name='External code')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Last modified')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
            ],
            options={
                'verbose_name': 'Insurence',
                'verbose_name_plural': 'Insurences',
            },
        ),
        migrations.CreateModel(
            name='LabelPrinters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Printer barcode name', max_length=100, verbose_name='Name')),
                ('active', models.BooleanField(default=True, verbose_name='is active?')),
                ('com_port', models.CharField(help_text='eq: COM10,COM11', max_length=100, verbose_name='Com serial port name')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Last modified')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='Order date')),
                ('number', models.CharField(blank=True, default=bbconnlab.models.auto_order_no, max_length=100, null=True, unique=True, verbose_name='Number')),
                ('note', models.CharField(blank=True, max_length=100, null=True, verbose_name='Note/Comment')),
                ('dateofcreation', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Last modified')),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bbconnlab.Diagnosis', verbose_name='Diagnosis')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bbconnlab.Doctors', verbose_name='Sender doctor')),
                ('insurance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bbconnlab.Insurance', verbose_name='Insurance')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
            ],
            options={
                'ordering': ['number', 'origin'],
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'permissions': (('view_orders', 'Can view orders'),),
            },
        ),
        migrations.CreateModel(
            name='OrderSamples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_no', models.CharField(help_text='Sample id', max_length=100, verbose_name='sample id')),
                ('dateofcreation', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Last modified')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sample_order', to='bbconnlab.Orders', verbose_name='Order')),
            ],
            options={
                'ordering': ['order', 'sample_no'],
                'verbose_name': 'Order samples',
                'verbose_name_plural': 'Order samples',
                'permissions': (('view_ordersamples', 'Can view order samples'),),
            },
        ),
        migrations.CreateModel(
            name='OrderTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateofcreation', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Last modified')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='bbconnlab.Orders', verbose_name='Order')),
            ],
            options={
                'ordering': ['order', 'test'],
                'verbose_name': 'Order test',
                'verbose_name_plural': 'Order tests',
                'permissions': (('view_ordertests', 'Can view order tests'),),
            },
        ),
        migrations.CreateModel(
            name='Origins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Origin Name')),
                ('ext_code', models.CharField(max_length=30, verbose_name='External code')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Last modified')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
            ],
            options={
                'verbose_name': 'Origin',
                'verbose_name_plural': 'Origins',
            },
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('char_value', models.CharField(blank=True, max_length=100, null=True, verbose_name='Char value')),
                ('num_value', models.IntegerField(blank=True, null=True, verbose_name='Numeric value')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Last modified')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
            ],
            options={
                'verbose_name': 'Parameter',
                'verbose_name_plural': 'Parameters',
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(help_text='Medical record number', max_length=100, unique=True, verbose_name='Patient ID')),
                ('name', models.CharField(help_text='Patient Name', max_length=100, verbose_name='Name')),
                ('dob', models.DateField(help_text='Date format: DD-MM-YYYY', verbose_name='Date of birth')),
                ('address', models.CharField(help_text='Patient Address', max_length=100, verbose_name='Address')),
                ('data0', models.CharField(blank=True, help_text='Additional data 0', max_length=100, null=True, verbose_name='Data 0')),
                ('data1', models.CharField(blank=True, help_text='Additional data 1', max_length=100, null=True, verbose_name='Data 1')),
                ('data2', models.CharField(blank=True, help_text='Additional data 3', max_length=100, null=True, verbose_name='Data 2')),
                ('dateofcreation', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Last modified')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bbconnlab.Genders', verbose_name='Gender')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
            ],
            options={
                'ordering': ['patient_id', 'name'],
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'permissions': (('view_patients', 'Can view test patients'),),
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Group Name')),
                ('ext_code', models.CharField(max_length=30, verbose_name='External code')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Last modified')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
            ],
            options={
                'verbose_name': 'Priority',
                'verbose_name_plural': 'Priorities',
            },
        ),
        migrations.CreateModel(
            name='Specimens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Specimen Name')),
                ('suffix_code', models.CharField(max_length=3, verbose_name='Suffix code')),
            ],
            options={
                'verbose_name': 'Specimen',
                'verbose_name_plural': 'Specimens',
            },
        ),
        migrations.CreateModel(
            name='SuperGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=100, verbose_name='Abbreviation')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Last modified')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
            ],
        ),
        migrations.CreateModel(
            name='TestGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Group Name')),
                ('sort', models.IntegerField(help_text='Sorted priority', verbose_name='Sort')),
                ('dateofcreation', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Last modified')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('supergroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='testgroup_supergroup', to='bbconnlab.SuperGroups', verbose_name='Super Group')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Test group',
                'verbose_name_plural': 'Test groups',
                'permissions': (('view_testgroups', 'Can view testgroups'),),
            },
        ),
        migrations.CreateModel(
            name='TestPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff', models.DecimalField(decimal_places=2, help_text='base tariff', max_digits=20, verbose_name='tariff')),
                ('service', models.DecimalField(decimal_places=2, help_text='Medical service rate', max_digits=20, verbose_name='Medc.Serv')),
                ('dateofcreation', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Last modified')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bbconnlab.Priority', verbose_name='Priority')),
            ],
            options={
                'ordering': ['test', 'priority'],
                'verbose_name': 'Test price',
                'verbose_name_plural': 'Test prices',
                'permissions': (('view_testprices', 'Can view test prices'),),
            },
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Test Name')),
                ('result_type', models.CharField(choices=[('NUM', 'NUMERIC'), ('ALF', 'ALFANUMERIC'), ('TXT', 'TEXT'), ('IMG', 'IMAGE')], default='NUM', max_length=3, verbose_name='Result Type')),
                ('can_request', models.BooleanField(default=True, verbose_name='Can request?')),
                ('sort', models.IntegerField(help_text='Sorted priority', verbose_name='Sort')),
                ('ext_code', models.CharField(max_length=30, verbose_name='External code')),
                ('dateofcreation', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Last modified')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='bbconnlab.Tests')),
                ('specimen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='test_specimen', to='bbconnlab.Specimens', verbose_name='Specimen')),
                ('test_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='bbconnlab.TestGroups', verbose_name='Test Group')),
            ],
            options={
                'ordering': ['test_group', 'name'],
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
                'permissions': (('view_tests', 'Can view tests'),),
            },
        ),
        migrations.AddField(
            model_name='testprices',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_price', to='bbconnlab.Tests', verbose_name='Test'),
        ),
        migrations.AddField(
            model_name='ordertests',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_tests', to='bbconnlab.Tests', verbose_name='Test'),
        ),
        migrations.AddField(
            model_name='ordersamples',
            name='specimen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sample_specimen', to='bbconnlab.Specimens', verbose_name='Specimen'),
        ),
        migrations.AddField(
            model_name='orders',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bbconnlab.Origins', verbose_name='Origin'),
        ),
        migrations.AddField(
            model_name='orders',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bbconnlab.Patients', verbose_name='Patient'),
        ),
        migrations.AddField(
            model_name='orders',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bbconnlab.Priority', verbose_name='Order priority'),
        ),
    ]
