# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-16 09:15
from __future__ import unicode_literals

import bbconnlab.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh')),
            ],
        ),
        migrations.CreateModel(
            name='BatchGroupTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah')),
                ('batch_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batchtest_batchgroup', to='bbconnlab.BatchGroups', verbose_name='Grup batch')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama diagnosa')),
                ('ext_code', models.CharField(max_length=30, verbose_name='Kode eksternal')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh')),
            ],
            options={
                'verbose_name': 'Diagnosa',
                'verbose_name_plural': 'Diagnosa',
            },
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama dokter')),
                ('ext_code', models.CharField(max_length=30, verbose_name='Kode eksternal')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh')),
            ],
            options={
                'verbose_name': 'Dokter',
                'verbose_name_plural': 'Dokter',
            },
        ),
        migrations.CreateModel(
            name='Genders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama jns. Kelamin')),
                ('code', models.CharField(max_length=30, null=True, verbose_name='Kode')),
                ('ext_code', models.CharField(max_length=30, verbose_name='Kode eksternal')),
                ('inst_code', models.CharField(max_length=30, null=True, verbose_name='Instrument code')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh')),
            ],
            options={
                'verbose_name': 'Jenis kelamin',
                'verbose_name_plural': 'Jenis kelamin',
            },
        ),
        migrations.CreateModel(
            name='HistoryOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_code', models.CharField(max_length=20, null=True, verbose_name='Kode aksi')),
                ('action_user', models.CharField(max_length=20, null=True, verbose_name='Aksi oleh')),
                ('action_date', models.DateTimeField(null=True, verbose_name='Tanggal aksi')),
                ('action_text', models.CharField(max_length=1000, null=True, verbose_name='Text aksi')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh')),
            ],
        ),
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Kode')),
                ('name', models.CharField(max_length=100, verbose_name='Nama')),
                ('active', models.BooleanField(default=True, verbose_name='Aktif?')),
                ('input_path', models.CharField(max_length=100, verbose_name='input path')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentFlags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_code', models.CharField(max_length=100, verbose_name='kode flag host')),
                ('flag_description', models.CharField(max_length=100, verbose_name='Deskripsi flag host')),
                ('flag_mark', models.CharField(blank=True, max_length=100, null=True, verbose_name='Flag mark host')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah')),
            ],
        ),
        migrations.CreateModel(
            name='Instruments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Kode')),
                ('name', models.CharField(max_length=100, verbose_name='Nama')),
                ('active', models.BooleanField(default=True, verbose_name='Aktif?')),
                ('driver', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama driver')),
                ('connection_type', models.CharField(blank=True, choices=[('SER', 'Serial'), ('TCP', 'TCP/IP')], max_length=3, null=True, verbose_name='Tipe koneksi')),
                ('serial_port', models.CharField(blank=True, choices=[('COM1', 'COM1'), ('COM2', 'COM2'), ('COM3', 'COM3'), ('COM4', 'COM4'), ('COM5', 'COM5'), ('COM6', 'COM6'), ('COM7', 'COM7'), ('COM8', 'COM8'), ('COM9', 'COM9'), ('COM10', 'COM10'), ('COM11', 'COM11'), ('COM12', 'COM12'), ('COM13', 'COM13'), ('COM14', 'COM14'), ('COM15', 'COM15'), ('COM16', 'COM16'), ('COM17', 'COM17'), ('COM18', 'COM18'), ('COM19', 'COM19'), ('COM20', 'COM20'), ('COM21', 'COM21'), ('COM22', 'COM22'), ('COM23', 'COM23'), ('COM24', 'COM24'), ('COM25', 'COM25'), ('COM26', 'COM26'), ('COM27', 'COM27'), ('COM28', 'COM28'), ('COM29', 'COM29'), ('COM30', 'COM30'), ('COM31', 'COM31'), ('COM32', 'COM32'), ('COM33', 'COM33'), ('COM34', 'COM34'), ('COM35', 'COM35'), ('COM36', 'COM36'), ('COM37', 'COM37'), ('COM38', 'COM38'), ('COM39', 'COM39'), ('COM40', 'COM40')], max_length=3, null=True, verbose_name='Nama port serial')),
                ('serial_baud_rate', models.CharField(blank=True, choices=[('9600', '9600'), ('19200', '19200')], max_length=3, null=True, verbose_name='Serial baud rate')),
                ('serial_stop_bit', models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=3, null=True, verbose_name='Serial stop bit')),
                ('serial_data_bit', models.CharField(blank=True, choices=[('N', 'None'), ('E', 'Even')], max_length=3, null=True, verbose_name='Serial parity')),
                ('tcp_conn_type', models.CharField(blank=True, choices=[('S', 'Server'), ('C', 'Client')], max_length=3, null=True, verbose_name='Tipe koneksi TCP/IP')),
                ('tcp_host', models.GenericIPAddressField(blank=True, null=True, verbose_name='Nama TCP Host (IP Address)')),
                ('tcp_port', models.IntegerField(blank=True, null=True, verbose_name='Port TCP')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_code', models.CharField(max_length=100, verbose_name='Kode tes host')),
                ('result_type', models.CharField(choices=[('R', 'RAW'), ('N', 'NUMBERIC'), ('A', 'ALFANUMERIC')], default='R', max_length=3, verbose_name='Tipe hasil')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instrumentflags_instrument', to='bbconnlab.Instruments', verbose_name='Instrumen')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Insurance Name')),
                ('ext_code', models.CharField(max_length=30, verbose_name='Kode eksternal')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh')),
            ],
            options={
                'verbose_name': 'Angakatan',
                'verbose_name_plural': 'Angkatan',
            },
        ),
        migrations.CreateModel(
            name='LabelPrinters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nama printer barcode', max_length=100, verbose_name='Nama')),
                ('active', models.BooleanField(default=True, verbose_name='apakah aktif?')),
                ('com_port', models.CharField(help_text='mis: COM10,COM11', max_length=100, verbose_name='Nama port COM serial')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDiagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateofcreation', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_diagnosis', to='bbconnlab.Diagnosis', verbose_name='Diagnosa')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh')),
            ],
            options={
                'ordering': ['order', 'diagnosis'],
                'verbose_name': 'Order diagnosis',
                'verbose_name_plural': 'Order diagnosis',
                'permissions': (('view_ordertests', 'Can view order tests'),),
            },
        ),
        migrations.CreateModel(
            name='OrderResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_header', models.BooleanField(default=False, verbose_name='apakah header?')),
                ('unit', models.CharField(max_length=100, null=True, verbose_name='Unit hasil')),
                ('ref_range', models.CharField(max_length=200, null=True, verbose_name='Nilai normal')),
                ('patologi_mark', models.CharField(max_length=20, null=True, verbose_name='Patologi mark')),
                ('validation_status', models.IntegerField(default=0, verbose_name='Status validasi')),
                ('techval_user', models.CharField(max_length=20, null=True, verbose_name='Divalidasi teknis oleh')),
                ('techval_date', models.DateTimeField(null=True, verbose_name='Divalidasi teknis tanggal')),
                ('medval_user', models.CharField(max_length=20, null=True, verbose_name='Divalidasi medis oleh')),
                ('medval_date', models.DateTimeField(null=True, verbose_name='Divalidasi medis tanggal')),
                ('print_status', models.IntegerField(default=0, verbose_name='Status cetak')),
                ('print_user', models.CharField(max_length=20, null=True, verbose_name='Dicetak oleh')),
                ('print_date', models.DateTimeField(null=True, verbose_name='Tanggal cetak')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh')),
            ],
            options={
                'permissions': (('techval', 'Technical validating results'), ('medval', 'Medical validating result'), ('repeat', 'Repeating result')),
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='Tanggal order')),
                ('number', models.CharField(blank=True, default=bbconnlab.models.auto_order_no, max_length=100, null=True, unique=True, verbose_name='Nomor')),
                ('note', models.CharField(blank=True, max_length=100, null=True, verbose_name='Catatan/Komentar')),
                ('conclusion', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Kesimpulan')),
                ('dateofcreation', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah')),
            ],
            options={
                'ordering': ['number', 'origin'],
                'verbose_name': 'Order',
                'verbose_name_plural': 'Order',
                'permissions': (('view_orders', 'Can view orders'),),
            },
        ),
        migrations.CreateModel(
            name='OrderSamples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_no', models.CharField(help_text='Id sampel', max_length=100, verbose_name='id sampel')),
                ('dateofcreation', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh')),
            ],
            options={
                'ordering': ['order', 'sample_no'],
                'verbose_name': 'Sampel order',
                'verbose_name_plural': 'Sampel order',
                'permissions': (('view_ordersamples', 'Can view order samples'),),
            },
        ),
        migrations.CreateModel(
            name='OrderTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateofcreation', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh')),
            ],
            options={
                'ordering': ['order', 'test'],
                'verbose_name': 'Tes order',
                'verbose_name_plural': 'Tes order',
                'permissions': (('view_ordertests', 'Can view order tests'),),
            },
        ),
        migrations.CreateModel(
            name='Origins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama asal')),
                ('ext_code', models.CharField(max_length=30, verbose_name='Kode eksternal')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh')),
            ],
            options={
                'verbose_name': 'Asal',
                'verbose_name_plural': 'Asal',
            },
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama')),
                ('char_value', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nilai karakter')),
                ('num_value', models.IntegerField(blank=True, null=True, verbose_name='Nilai angka')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh')),
            ],
            options={
                'verbose_name': 'Parameter',
                'verbose_name_plural': 'Parameter',
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(help_text='Nomor rekam medis', max_length=100, unique=True, verbose_name='ID Pasien')),
                ('name', models.CharField(help_text='Nama pasien', max_length=100, verbose_name='Nama')),
                ('dob', models.DateField(help_text='Format tanggal: DD-MM-YYYY', verbose_name='Tanggal lahir')),
                ('address', models.CharField(help_text='Alamat pasien', max_length=100, verbose_name='Alamat')),
                ('data0', models.CharField(blank=True, help_text='Tambahan data 0', max_length=100, null=True, verbose_name='Data 0')),
                ('data1', models.CharField(blank=True, help_text='Tambahan data 1', max_length=100, null=True, verbose_name='Data 1')),
                ('data2', models.CharField(blank=True, help_text='Tambahan data 3', max_length=100, null=True, verbose_name='Data 2')),
                ('dateofcreation', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, null=True, verbose_name='Dibuat pada')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bbconnlab.Genders', verbose_name='Jenis kelamin')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh')),
            ],
            options={
                'ordering': ['patient_id', 'name'],
                'verbose_name': 'Pasien',
                'verbose_name_plural': 'Pasien',
                'permissions': (('view_patients', 'Can view test patients'),),
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama grup')),
                ('ext_code', models.CharField(max_length=30, verbose_name='Kode eksternal')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh')),
            ],
            options={
                'verbose_name': 'Prioritas',
                'verbose_name_plural': 'Prioritas',
            },
        ),
        migrations.CreateModel(
            name='ReceivedSamples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_result', models.FloatField(null=True, verbose_name='Hasil numerik')),
                ('alfa_result', models.CharField(max_length=100, null=True, verbose_name='Hasil alfanumerik')),
                ('text_result', models.TextField(null=True, verbose_name='Hasil text')),
                ('image_result', models.BinaryField(null=True, verbose_name='Hasil gambar')),
                ('ref_range', models.CharField(max_length=100, null=True, verbose_name='Nilai normal')),
                ('mark', models.CharField(max_length=3, null=True, verbose_name='Mark hasil')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah')),
                ('flag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='results_instrumentflag', to='bbconnlab.InstrumentFlags', verbose_name='Flag instrument')),
                ('instrument', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='results_instrument', to='bbconnlab.Instruments', verbose_name='Instrumen')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Service Name')),
                ('ext_code', models.CharField(max_length=30, verbose_name='Kode eksternal')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Specimens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama spesimen')),
                ('suffix_code', models.CharField(max_length=3, verbose_name='Kode akhiran')),
            ],
            options={
                'verbose_name': 'Spesimen',
                'verbose_name_plural': 'Spesimen',
            },
        ),
        migrations.CreateModel(
            name='SuperGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=100, verbose_name='Singkatan')),
                ('name', models.CharField(max_length=100, verbose_name='Nama')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh')),
            ],
        ),
        migrations.CreateModel(
            name='TestGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama grup')),
                ('sort', models.IntegerField(help_text='Urutan prioritas', verbose_name='Urut')),
                ('dateofcreation', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh')),
                ('supergroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='testgroup_supergroup', to='bbconnlab.SuperGroups', verbose_name='Grup super')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Grup tes',
                'verbose_name_plural': 'Grup tes',
                'permissions': (('view_testgroups', 'Can view testgroups'),),
            },
        ),
        migrations.CreateModel(
            name='TestPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff', models.DecimalField(decimal_places=2, help_text='tarif dasar', max_digits=20, verbose_name='tarif')),
                ('service', models.DecimalField(decimal_places=2, help_text='Tarif layanan medis', max_digits=20, verbose_name='Pelayanan medis')),
                ('dateofcreation', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bbconnlab.Priority', verbose_name='Prioritas')),
            ],
            options={
                'ordering': ['test', 'priority'],
                'verbose_name': 'Harga tes',
                'verbose_name_plural': 'Harga tes',
                'permissions': (('view_testprices', 'Can view test prices'),),
            },
        ),
        migrations.CreateModel(
            name='TestRefRanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_from', models.IntegerField(blank=True, null=True, verbose_name='Usia dari')),
                ('age_from_type', models.CharField(blank=True, choices=[('D', 'DAY'), ('M', 'MONTH'), ('Y', 'YEAR')], max_length=3, null=True, verbose_name='Usia dari unit')),
                ('age_to', models.IntegerField(blank=True, null=True, verbose_name='Usia sampai')),
                ('age_to_type', models.CharField(blank=True, choices=[('D', 'DAY'), ('M', 'MONTH'), ('Y', 'YEAR')], max_length=3, null=True, verbose_name='Usia sampai unit')),
                ('operator', models.CharField(blank=True, choices=[('-', 'NA'), ('>', 'GT'), ('>=', 'GTE'), ('<', 'LT'), ('<=', 'LTE')], max_length=3, null=True, verbose_name='Operator')),
                ('any_age', models.BooleanField(default=True, verbose_name='Semua umur?')),
                ('lower', models.IntegerField(blank=True, null=True, verbose_name='Batas bawah')),
                ('upper', models.IntegerField(blank=True, null=True, verbose_name='Batas atas')),
                ('operator_value', models.IntegerField(blank=True, null=True, verbose_name='Nilai operator')),
                ('alfa_value', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nilai alfanumerik')),
                ('special_info', models.TextField(blank=True, null=True, verbose_name='Informasi spesial')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refranges_gender', to='bbconnlab.Genders', verbose_name='Jenis kelamin')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh')),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nama tes')),
                ('result_type', models.CharField(choices=[('NUM', 'NUMERIC'), ('ALF', 'ALFANUMERIC'), ('TXT', 'TEXT'), ('IMG', 'IMAGE')], default='NUM', max_length=3, verbose_name='Tipe hasil')),
                ('can_request', models.BooleanField(default=True, verbose_name='Dapat di-request')),
                ('sort', models.IntegerField(help_text='Urutan prioritas', verbose_name='Urut')),
                ('ext_code', models.CharField(max_length=30, verbose_name='Kode eksternal')),
                ('dateofcreation', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah')),
            ],
            options={
                'ordering': ['test_group', 'name'],
                'verbose_name': 'Tes',
                'verbose_name_plural': 'Tes',
                'permissions': (('view_tests', 'Can view tests'),),
            },
        ),
        migrations.CreateModel(
            name='WorklistOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh')),
            ],
        ),
        migrations.CreateModel(
            name='Worklists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_date', models.DateField(auto_now_add=True, verbose_name='Tanggal batch')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah')),
                ('batch_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worklist_batchgroup', to='bbconnlab.BatchGroups', verbose_name='Grup batch')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh')),
            ],
        ),
        migrations.CreateModel(
            name='WorklistTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh')),
            ],
        ),
        migrations.CreateModel(
            name='OrderExtended',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='bbconnlab.Orders')),
                ('result_pdf_url', models.CharField(max_length=500, null=True, verbose_name='url hasil PDF')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh')),
            ],
        ),
        migrations.CreateModel(
            name='TestParameters',
            fields=[
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='bbconnlab.Tests')),
                ('method', models.CharField(blank=True, max_length=100, null=True, verbose_name='Metode')),
                ('unit', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tes unit')),
                ('decimal_place', models.IntegerField(default=1, null=True, verbose_name='Tempat desimal')),
                ('special_information', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Informasi spesial')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh')),
            ],
        ),
        migrations.AddField(
            model_name='worklisttests',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worklisttest_test', to='bbconnlab.Tests', verbose_name='Tes'),
        ),
        migrations.AddField(
            model_name='worklisttests',
            name='worklistorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worklisttest_worklistorder', to='bbconnlab.WorklistOrders', verbose_name='Daftar pekerjaan order'),
        ),
        migrations.AddField(
            model_name='worklistorders',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worklistorder_order', to='bbconnlab.Orders', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='worklistorders',
            name='worklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worklist_order', to='bbconnlab.Worklists', verbose_name='Daftar pekerjaan'),
        ),
        migrations.AddField(
            model_name='tests',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh'),
        ),
        migrations.AddField(
            model_name='tests',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='bbconnlab.Tests'),
        ),
        migrations.AddField(
            model_name='tests',
            name='specimen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='test_specimen', to='bbconnlab.Specimens', verbose_name='Spesimen'),
        ),
        migrations.AddField(
            model_name='tests',
            name='test_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='bbconnlab.TestGroups', verbose_name='Grup tes'),
        ),
        migrations.AddField(
            model_name='testrefranges',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refranges_test', to='bbconnlab.Tests', verbose_name='Tes'),
        ),
        migrations.AddField(
            model_name='testprices',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_price', to='bbconnlab.Tests', verbose_name='Tes'),
        ),
        migrations.AddField(
            model_name='results',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results_order', to='bbconnlab.Orders', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='results',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results_test', to='bbconnlab.Tests', verbose_name='Tes'),
        ),
        migrations.AddField(
            model_name='receivedsamples',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivedsamples_order', to='bbconnlab.Orders', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='receivedsamples',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivedsamples_tube', to='bbconnlab.OrderSamples', verbose_name='Spesimen'),
        ),
        migrations.AddField(
            model_name='receivedsamples',
            name='supergroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivedsamples_supergrup', to='bbconnlab.SuperGroups', verbose_name='Grup super'),
        ),
        migrations.AddField(
            model_name='ordertests',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='bbconnlab.Orders', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='ordertests',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_tests', to='bbconnlab.Tests', verbose_name='Tes'),
        ),
        migrations.AddField(
            model_name='ordersamples',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sample_order', to='bbconnlab.Orders', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='ordersamples',
            name='specimen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sample_specimen', to='bbconnlab.Specimens', verbose_name='Spesimen'),
        ),
        migrations.AddField(
            model_name='orders',
            name='diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bbconnlab.Diagnosis', verbose_name='Diagnosa'),
        ),
        migrations.AddField(
            model_name='orders',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bbconnlab.Doctors', verbose_name='Dokter pengirim'),
        ),
        migrations.AddField(
            model_name='orders',
            name='insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bbconnlab.Insurance', verbose_name='Angkatan'),
        ),
        migrations.AddField(
            model_name='orders',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh'),
        ),
        migrations.AddField(
            model_name='orders',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bbconnlab.Origins', verbose_name='Asal'),
        ),
        migrations.AddField(
            model_name='orders',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bbconnlab.Patients', verbose_name='Pasien'),
        ),
        migrations.AddField(
            model_name='orders',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bbconnlab.Priority', verbose_name='Prioritas order'),
        ),
        migrations.AddField(
            model_name='orders',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bbconnlab.Service', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='orderresults',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderresults_order', to='bbconnlab.Orders', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='orderresults',
            name='result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orderresults_result', to='bbconnlab.Results', verbose_name='Hasil'),
        ),
        migrations.AddField(
            model_name='orderresults',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sampleresults_order', to='bbconnlab.OrderSamples', verbose_name='Sampel Order'),
        ),
        migrations.AddField(
            model_name='orderresults',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orderresults_test', to='bbconnlab.Tests', verbose_name='Tes'),
        ),
        migrations.AddField(
            model_name='orderdiagnosis',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_diagitems', to='bbconnlab.Orders', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='instrumenttests',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instrumentflags_test', to='bbconnlab.Tests', verbose_name='Tes'),
        ),
        migrations.AddField(
            model_name='instrumentflags',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instrumenttests_instrument', to='bbconnlab.Instruments', verbose_name='Instrumen'),
        ),
        migrations.AddField(
            model_name='instrumentflags',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh'),
        ),
        migrations.AddField(
            model_name='historyorders',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historyorder_order', to='bbconnlab.Orders', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='historyorders',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historyorder_test', to='bbconnlab.Tests', verbose_name='Tes'),
        ),
        migrations.AddField(
            model_name='batchgrouptests',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batchgroup_test', to='bbconnlab.Tests', verbose_name='Tes'),
        ),
        migrations.AlterUniqueTogether(
            name='orderresults',
            unique_together=set([('order', 'test')]),
        ),
    ]
