# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbconnlab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supergroups',
            name='is_workarea',
            field=models.BooleanField(default=0, verbose_name='Nama'),
        ),
    ]
