# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 21:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bbconnlab', '0002_supergroups_is_workarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorakareaTestGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(help_text='Urutan prioritas', verbose_name='Urut')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh')),
            ],
            options={
                'ordering': ['sort'],
                'verbose_name': 'Area kerja',
                'verbose_name_plural': 'Area kerja',
                'permissions': (('view_workarea', 'Can view worakarea'),),
            },
        ),
        migrations.CreateModel(
            name='Workarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Area kerja',
                'verbose_name_plural': 'Area kerja',
                'permissions': (('view_workarea', 'Can view worakarea'),),
            },
        ),
        migrations.AlterModelOptions(
            name='supergroups',
            options={'ordering': ['name'], 'permissions': (('view_supergroups', 'Can view supergroups'),), 'verbose_name': 'Super group', 'verbose_name_plural': 'Super groups'},
        ),
        migrations.RemoveField(
            model_name='supergroups',
            name='is_workarea',
        ),
        migrations.AddField(
            model_name='worakareatestgroups',
            name='woarkarea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='testgroup_workarea', to='bbconnlab.Workarea', verbose_name='Area kerja'),
        ),
    ]
