# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-14 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbconnlab', '0002_auto_20180714_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='conclusion',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Conclusion'),
        ),
    ]
