# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-14 20:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bbconnlab', '0003_orders_conclusion'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Last modified')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
            ],
        ),
        migrations.CreateModel(
            name='BatchGroupTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Last modified')),
                ('batch_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batchtest_batchgroup', to='bbconnlab.BatchGroups', verbose_name='Batch group')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batchgroup_test', to='bbconnlab.Tests', verbose_name='Test')),
            ],
        ),
        migrations.CreateModel(
            name='WorklistOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Last modified')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worklistorder_order', to='bbconnlab.Orders', verbose_name='Order')),
            ],
        ),
        migrations.CreateModel(
            name='Worklists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_date', models.DateField(auto_now_add=True, verbose_name='Batch date')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Last modified')),
                ('batch_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worklist_batchgroup', to='bbconnlab.BatchGroups', verbose_name='Batch group')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
            ],
        ),
        migrations.CreateModel(
            name='WorklistTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Last modified')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worklisttest_test', to='bbconnlab.Tests', verbose_name='Test')),
                ('worklistorder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worklisttest_worklistorder', to='bbconnlab.WorklistOrders', verbose_name='Worklist order')),
            ],
        ),
        migrations.AddField(
            model_name='genders',
            name='code',
            field=models.CharField(max_length=30, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='historyorders',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historyorder_test', to='bbconnlab.Tests', verbose_name='Test'),
        ),
        migrations.AddField(
            model_name='worklistorders',
            name='worklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worklist_order', to='bbconnlab.Worklists', verbose_name='Worklist'),
        ),
    ]
