# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbconnlab', '0003_auto_20181101_2123'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorakareaTestGroups',
            new_name='WorkareaTestGroups',
        ),
        migrations.AlterModelOptions(
            name='workarea',
            options={'ordering': ['name'], 'permissions': (('view_workarea', 'Can view worakarea'),), 'verbose_name': 'Area kerja', 'verbose_name_plural': 'Workareas'},
        ),
    ]
