# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 14:13
from __future__ import unicode_literals

import bbconnlab.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bbconnlab', '0004_auto_20180715_0340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'verbose_name': 'Diagnosa', 'verbose_name_plural': 'Diagnosa'},
        ),
        migrations.AlterModelOptions(
            name='doctors',
            options={'verbose_name': 'Dokter', 'verbose_name_plural': 'Dokter'},
        ),
        migrations.AlterModelOptions(
            name='genders',
            options={'verbose_name': 'Jenis kelamin', 'verbose_name_plural': 'Jenis kelamin'},
        ),
        migrations.AlterModelOptions(
            name='insurance',
            options={'verbose_name': 'Angakatan', 'verbose_name_plural': 'Angkatan'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['number', 'origin'], 'permissions': (('view_orders', 'Can view orders'),), 'verbose_name': 'Order', 'verbose_name_plural': 'Order'},
        ),
        migrations.AlterModelOptions(
            name='ordersamples',
            options={'ordering': ['order', 'sample_no'], 'permissions': (('view_ordersamples', 'Can view order samples'),), 'verbose_name': 'Sampel order', 'verbose_name_plural': 'Sampel order'},
        ),
        migrations.AlterModelOptions(
            name='ordertests',
            options={'ordering': ['order', 'test'], 'permissions': (('view_ordertests', 'Can view order tests'),), 'verbose_name': 'Tes order', 'verbose_name_plural': 'Tes order'},
        ),
        migrations.AlterModelOptions(
            name='origins',
            options={'verbose_name': 'Asal', 'verbose_name_plural': 'Asal'},
        ),
        migrations.AlterModelOptions(
            name='parameters',
            options={'verbose_name': 'Parameter', 'verbose_name_plural': 'Parameter'},
        ),
        migrations.AlterModelOptions(
            name='patients',
            options={'ordering': ['patient_id', 'name'], 'permissions': (('view_patients', 'Can view test patients'),), 'verbose_name': 'Pasien', 'verbose_name_plural': 'Pasien'},
        ),
        migrations.AlterModelOptions(
            name='priority',
            options={'verbose_name': 'Prioritas', 'verbose_name_plural': 'Prioritas'},
        ),
        migrations.AlterModelOptions(
            name='specimens',
            options={'verbose_name': 'Spesimen', 'verbose_name_plural': 'Spesimen'},
        ),
        migrations.AlterModelOptions(
            name='testgroups',
            options={'ordering': ['name'], 'permissions': (('view_testgroups', 'Can view testgroups'),), 'verbose_name': 'Grup tes', 'verbose_name_plural': 'Grup tes'},
        ),
        migrations.AlterModelOptions(
            name='testprices',
            options={'ordering': ['test', 'priority'], 'permissions': (('view_testprices', 'Can view test prices'),), 'verbose_name': 'Harga tes', 'verbose_name_plural': 'Harga tes'},
        ),
        migrations.AlterModelOptions(
            name='tests',
            options={'ordering': ['test_group', 'name'], 'permissions': (('view_tests', 'Can view tests'),), 'verbose_name': 'Tes', 'verbose_name_plural': 'Tes'},
        ),
        migrations.AlterField(
            model_name='batchgroups',
            name='lastmodification',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah'),
        ),
        migrations.AlterField(
            model_name='batchgroups',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh'),
        ),
        migrations.AlterField(
            model_name='batchgroups',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nama'),
        ),
        migrations.AlterField(
            model_name='batchgrouptests',
            name='batch_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batchtest_batchgroup', to='bbconnlab.BatchGroups', verbose_name='Grup batch'),
        ),
        migrations.AlterField(
            model_name='batchgrouptests',
            name='lastmodification',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah'),
        ),
        migrations.AlterField(
            model_name='batchgrouptests',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh'),
        ),
        migrations.AlterField(
            model_name='batchgrouptests',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batchgroup_test', to='bbconnlab.Tests', verbose_name='Tes'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='ext_code',
            field=models.CharField(max_length=30, verbose_name='Kode eksternal'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='lastmodification',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nama diagnosa'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='ext_code',
            field=models.CharField(max_length=30, verbose_name='Kode eksternal'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='lastmodification',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nama dokter'),
        ),
        migrations.AlterField(
            model_name='genders',
            name='code',
            field=models.CharField(max_length=30, null=True, verbose_name='Kode'),
        ),
        migrations.AlterField(
            model_name='genders',
            name='ext_code',
            field=models.CharField(max_length=30, verbose_name='Kode eksternal'),
        ),
        migrations.AlterField(
            model_name='genders',
            name='lastmodification',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah'),
        ),
        migrations.AlterField(
            model_name='genders',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh'),
        ),
        migrations.AlterField(
            model_name='genders',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nama jns. Kelamin'),
        ),
        migrations.AlterField(
            model_name='historyorders',
            name='action_code',
            field=models.CharField(max_length=20, null=True, verbose_name='Kode aksi'),
        ),
        migrations.AlterField(
            model_name='historyorders',
            name='action_date',
            field=models.DateTimeField(null=True, verbose_name='Tanggal aksi'),
        ),
        migrations.AlterField(
            model_name='historyorders',
            name='action_text',
            field=models.CharField(max_length=1000, null=True, verbose_name='Text aksi'),
        ),
        migrations.AlterField(
            model_name='historyorders',
            name='action_user',
            field=models.CharField(max_length=20, null=True, verbose_name='Aksi oleh'),
        ),
        migrations.AlterField(
            model_name='historyorders',
            name='lastmodification',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah'),
        ),
        migrations.AlterField(
            model_name='historyorders',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh'),
        ),
        migrations.AlterField(
            model_name='historyorders',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historyorder_test', to='bbconnlab.Tests', verbose_name='Tes'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktif?'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Kode'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='lastmodification',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nama'),
        ),
        migrations.AlterField(
            model_name='instrumentflags',
            name='flag_code',
            field=models.CharField(max_length=100, verbose_name='kode flag host'),
        ),
        migrations.AlterField(
            model_name='instrumentflags',
            name='flag_description',
            field=models.CharField(max_length=100, verbose_name='Deskripsi flag host'),
        ),
        migrations.AlterField(
            model_name='instrumentflags',
            name='flag_mark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Flag mark host'),
        ),
        migrations.AlterField(
            model_name='instrumentflags',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instrumenttests_instrument', to='bbconnlab.Instruments', verbose_name='Instrumen'),
        ),
        migrations.AlterField(
            model_name='instrumentflags',
            name='lastmodification',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah'),
        ),
        migrations.AlterField(
            model_name='instrumentflags',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh'),
        ),
        migrations.AlterField(
            model_name='instruments',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktif?'),
        ),
        migrations.AlterField(
            model_name='instruments',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Kode'),
        ),
        migrations.AlterField(
            model_name='instruments',
            name='connection_type',
            field=models.CharField(blank=True, choices=[('SER', 'Serial'), ('TCP', 'TCP/IP')], max_length=3, null=True, verbose_name='Tipe koneksi'),
        ),
        migrations.AlterField(
            model_name='instruments',
            name='driver',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama driver'),
        ),
        migrations.AlterField(
            model_name='instruments',
            name='lastmodification',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah'),
        ),
        migrations.AlterField(
            model_name='instruments',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh'),
        ),
        migrations.AlterField(
            model_name='instruments',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nama'),
        ),
        migrations.AlterField(
            model_name='instruments',
            name='serial_port',
            field=models.CharField(blank=True, choices=[('COM1', 'COM1'), ('COM2', 'COM2'), ('COM3', 'COM3'), ('COM4', 'COM4'), ('COM5', 'COM5'), ('COM6', 'COM6'), ('COM7', 'COM7'), ('COM8', 'COM8'), ('COM9', 'COM9'), ('COM10', 'COM10'), ('COM11', 'COM11'), ('COM12', 'COM12'), ('COM13', 'COM13'), ('COM14', 'COM14'), ('COM15', 'COM15'), ('COM16', 'COM16'), ('COM17', 'COM17'), ('COM18', 'COM18'), ('COM19', 'COM19'), ('COM20', 'COM20'), ('COM21', 'COM21'), ('COM22', 'COM22'), ('COM23', 'COM23'), ('COM24', 'COM24'), ('COM25', 'COM25'), ('COM26', 'COM26'), ('COM27', 'COM27'), ('COM28', 'COM28'), ('COM29', 'COM29'), ('COM30', 'COM30'), ('COM31', 'COM31'), ('COM32', 'COM32'), ('COM33', 'COM33'), ('COM34', 'COM34'), ('COM35', 'COM35'), ('COM36', 'COM36'), ('COM37', 'COM37'), ('COM38', 'COM38'), ('COM39', 'COM39'), ('COM40', 'COM40')], max_length=3, null=True, verbose_name='Nama port serial'),
        ),
        migrations.AlterField(
            model_name='instruments',
            name='tcp_conn_type',
            field=models.CharField(blank=True, choices=[('S', 'Server'), ('C', 'Client')], max_length=3, null=True, verbose_name='Tipe koneksi TCP/IP'),
        ),
        migrations.AlterField(
            model_name='instruments',
            name='tcp_host',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Nama TCP Host (IP Address)'),
        ),
        migrations.AlterField(
            model_name='instruments',
            name='tcp_port',
            field=models.IntegerField(blank=True, null=True, verbose_name='Port TCP'),
        ),
        migrations.AlterField(
            model_name='instrumenttests',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instrumentflags_instrument', to='bbconnlab.Instruments', verbose_name='Instrumen'),
        ),
        migrations.AlterField(
            model_name='instrumenttests',
            name='lastmodification',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah'),
        ),
        migrations.AlterField(
            model_name='instrumenttests',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh'),
        ),
        migrations.AlterField(
            model_name='instrumenttests',
            name='result_type',
            field=models.CharField(choices=[('R', 'RAW'), ('N', 'NUMBERIC'), ('A', 'ALFANUMERIC')], default='R', max_length=3, verbose_name='Tipe hasil'),
        ),
        migrations.AlterField(
            model_name='instrumenttests',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instrumentflags_test', to='bbconnlab.Tests', verbose_name='Tes'),
        ),
        migrations.AlterField(
            model_name='instrumenttests',
            name='test_code',
            field=models.CharField(max_length=100, verbose_name='Kode tes host'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='ext_code',
            field=models.CharField(max_length=30, verbose_name='Kode eksternal'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='lastmodification',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Insurance Name'),
        ),
        migrations.AlterField(
            model_name='labelprinters',
            name='active',
            field=models.BooleanField(default=True, verbose_name='apakah aktif?'),
        ),
        migrations.AlterField(
            model_name='labelprinters',
            name='com_port',
            field=models.CharField(help_text='mis: COM10,COM11', max_length=100, verbose_name='Nama port COM serial'),
        ),
        migrations.AlterField(
            model_name='labelprinters',
            name='lastmodification',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah'),
        ),
        migrations.AlterField(
            model_name='labelprinters',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh'),
        ),
        migrations.AlterField(
            model_name='labelprinters',
            name='name',
            field=models.CharField(help_text='Nama printer barcode', max_length=100, verbose_name='Nama'),
        ),
        migrations.AlterField(
            model_name='orderextended',
            name='lastmodification',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah'),
        ),
        migrations.AlterField(
            model_name='orderextended',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh'),
        ),
        migrations.AlterField(
            model_name='orderextended',
            name='result_pdf_url',
            field=models.CharField(max_length=500, null=True, verbose_name='url hasil PDF'),
        ),
        migrations.AlterField(
            model_name='orderresults',
            name='is_header',
            field=models.BooleanField(default=False, verbose_name='apakah header?'),
        ),
        migrations.AlterField(
            model_name='orderresults',
            name='lastmodification',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah'),
        ),
        migrations.AlterField(
            model_name='orderresults',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh'),
        ),
        migrations.AlterField(
            model_name='orderresults',
            name='medval_date',
            field=models.DateTimeField(null=True, verbose_name='Divalidasi medis tanggal'),
        ),
        migrations.AlterField(
            model_name='orderresults',
            name='medval_user',
            field=models.CharField(max_length=20, null=True, verbose_name='Divalidasi medis oleh'),
        ),
        migrations.AlterField(
            model_name='orderresults',
            name='print_date',
            field=models.DateTimeField(null=True, verbose_name='Tanggal cetak'),
        ),
        migrations.AlterField(
            model_name='orderresults',
            name='print_status',
            field=models.IntegerField(default=0, verbose_name='Status cetak'),
        ),
        migrations.AlterField(
            model_name='orderresults',
            name='print_user',
            field=models.CharField(max_length=20, null=True, verbose_name='Dicetak oleh'),
        ),
        migrations.AlterField(
            model_name='orderresults',
            name='ref_range',
            field=models.CharField(max_length=200, null=True, verbose_name='Nilai normal'),
        ),
        migrations.AlterField(
            model_name='orderresults',
            name='result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orderresults_result', to='bbconnlab.Results', verbose_name='Hasil'),
        ),
        migrations.AlterField(
            model_name='orderresults',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sampleresults_order', to='bbconnlab.OrderSamples', verbose_name='Sampel Order'),
        ),
        migrations.AlterField(
            model_name='orderresults',
            name='techval_date',
            field=models.DateTimeField(null=True, verbose_name='Divalidasi teknis tanggal'),
        ),
        migrations.AlterField(
            model_name='orderresults',
            name='techval_user',
            field=models.CharField(max_length=20, null=True, verbose_name='Divalidasi teknis oleh'),
        ),
        migrations.AlterField(
            model_name='orderresults',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderresults_test', to='bbconnlab.Tests', verbose_name='Tes'),
        ),
        migrations.AlterField(
            model_name='orderresults',
            name='unit',
            field=models.CharField(max_length=100, null=True, verbose_name='Unit hasil'),
        ),
        migrations.AlterField(
            model_name='orderresults',
            name='validation_status',
            field=models.IntegerField(default=0, verbose_name='Status validasi'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='conclusion',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Kesimpulan'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='dateofcreation',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Dibuat pada'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bbconnlab.Diagnosis', verbose_name='Diagnosa'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bbconnlab.Doctors', verbose_name='Dokter pengirim'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bbconnlab.Insurance', verbose_name='Angkatan'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='lastmodification',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Catatan/Komentar'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='number',
            field=models.CharField(blank=True, default=bbconnlab.models.auto_order_no, max_length=100, null=True, unique=True, verbose_name='Nomor'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateField(auto_now_add=True, verbose_name='Tanggal order'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bbconnlab.Origins', verbose_name='Asal'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bbconnlab.Patients', verbose_name='Pasien'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bbconnlab.Priority', verbose_name='Prioritas order'),
        ),
        migrations.AlterField(
            model_name='ordersamples',
            name='dateofcreation',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Dibuat pada'),
        ),
        migrations.AlterField(
            model_name='ordersamples',
            name='lastmodification',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah'),
        ),
        migrations.AlterField(
            model_name='ordersamples',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh'),
        ),
        migrations.AlterField(
            model_name='ordersamples',
            name='sample_no',
            field=models.CharField(help_text='Id sampel', max_length=100, verbose_name='id sampel'),
        ),
        migrations.AlterField(
            model_name='ordersamples',
            name='specimen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sample_specimen', to='bbconnlab.Specimens', verbose_name='Spesimen'),
        ),
        migrations.AlterField(
            model_name='ordertests',
            name='dateofcreation',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Dibuat pada'),
        ),
        migrations.AlterField(
            model_name='ordertests',
            name='lastmodification',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah'),
        ),
        migrations.AlterField(
            model_name='ordertests',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh'),
        ),
        migrations.AlterField(
            model_name='ordertests',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_tests', to='bbconnlab.Tests', verbose_name='Tes'),
        ),
        migrations.AlterField(
            model_name='origins',
            name='ext_code',
            field=models.CharField(max_length=30, verbose_name='Kode eksternal'),
        ),
        migrations.AlterField(
            model_name='origins',
            name='lastmodification',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah'),
        ),
        migrations.AlterField(
            model_name='origins',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh'),
        ),
        migrations.AlterField(
            model_name='origins',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nama asal'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='char_value',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nilai karakter'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='lastmodification',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nama'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='num_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nilai angka'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='address',
            field=models.CharField(help_text='Alamat pasien', max_length=100, verbose_name='Alamat'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='data0',
            field=models.CharField(blank=True, help_text='Tambahan data 0', max_length=100, null=True, verbose_name='Data 0'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='data1',
            field=models.CharField(blank=True, help_text='Tambahan data 1', max_length=100, null=True, verbose_name='Data 1'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='data2',
            field=models.CharField(blank=True, help_text='Tambahan data 3', max_length=100, null=True, verbose_name='Data 2'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='dateofcreation',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, null=True, verbose_name='Dibuat pada'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='dob',
            field=models.DateField(help_text='Format tanggal: DD-MM-YYYY', verbose_name='Tanggal lahir'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bbconnlab.Genders', verbose_name='Jenis kelamin'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='lastmodification',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='name',
            field=models.CharField(help_text='Nama pasien', max_length=100, verbose_name='Nama'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='patient_id',
            field=models.CharField(help_text='Nomor rekam medis', max_length=100, unique=True, verbose_name='ID Pasien'),
        ),
        migrations.AlterField(
            model_name='priority',
            name='ext_code',
            field=models.CharField(max_length=30, verbose_name='Kode eksternal'),
        ),
        migrations.AlterField(
            model_name='priority',
            name='lastmodification',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah'),
        ),
        migrations.AlterField(
            model_name='priority',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh'),
        ),
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nama grup'),
        ),
        migrations.AlterField(
            model_name='receivedsamples',
            name='lastmodification',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah'),
        ),
        migrations.AlterField(
            model_name='receivedsamples',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh'),
        ),
        migrations.AlterField(
            model_name='receivedsamples',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivedsamples_tube', to='bbconnlab.OrderSamples', verbose_name='Spesimen'),
        ),
        migrations.AlterField(
            model_name='receivedsamples',
            name='supergroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivedsamples_supergrup', to='bbconnlab.SuperGroups', verbose_name='Grup super'),
        ),
        migrations.AlterField(
            model_name='results',
            name='alfa_result',
            field=models.CharField(max_length=100, null=True, verbose_name='Hasil alfanumerik'),
        ),
        migrations.AlterField(
            model_name='results',
            name='flag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='results_instrumentflag', to='bbconnlab.InstrumentFlags', verbose_name='Flag instrument'),
        ),
        migrations.AlterField(
            model_name='results',
            name='image_result',
            field=models.BinaryField(null=True, verbose_name='Hasil gambar'),
        ),
        migrations.AlterField(
            model_name='results',
            name='instrument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='results_instrument', to='bbconnlab.Instruments', verbose_name='Instrumen'),
        ),
        migrations.AlterField(
            model_name='results',
            name='lastmodification',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah'),
        ),
        migrations.AlterField(
            model_name='results',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh'),
        ),
        migrations.AlterField(
            model_name='results',
            name='mark',
            field=models.CharField(max_length=3, null=True, verbose_name='Mark hasil'),
        ),
        migrations.AlterField(
            model_name='results',
            name='numeric_result',
            field=models.FloatField(null=True, verbose_name='Hasil numerik'),
        ),
        migrations.AlterField(
            model_name='results',
            name='ref_range',
            field=models.CharField(max_length=100, null=True, verbose_name='Nilai normal'),
        ),
        migrations.AlterField(
            model_name='results',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results_test', to='bbconnlab.Tests', verbose_name='Tes'),
        ),
        migrations.AlterField(
            model_name='results',
            name='text_result',
            field=models.TextField(null=True, verbose_name='Hasil text'),
        ),
        migrations.AlterField(
            model_name='specimens',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nama spesimen'),
        ),
        migrations.AlterField(
            model_name='specimens',
            name='suffix_code',
            field=models.CharField(max_length=3, verbose_name='Kode akhiran'),
        ),
        migrations.AlterField(
            model_name='supergroups',
            name='abbreviation',
            field=models.CharField(max_length=100, verbose_name='Singkatan'),
        ),
        migrations.AlterField(
            model_name='supergroups',
            name='lastmodification',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah'),
        ),
        migrations.AlterField(
            model_name='supergroups',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh'),
        ),
        migrations.AlterField(
            model_name='supergroups',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nama'),
        ),
        migrations.AlterField(
            model_name='testgroups',
            name='dateofcreation',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Dibuat pada'),
        ),
        migrations.AlterField(
            model_name='testgroups',
            name='lastmodification',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah'),
        ),
        migrations.AlterField(
            model_name='testgroups',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh'),
        ),
        migrations.AlterField(
            model_name='testgroups',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nama grup'),
        ),
        migrations.AlterField(
            model_name='testgroups',
            name='sort',
            field=models.IntegerField(help_text='Urutan prioritas', verbose_name='Urut'),
        ),
        migrations.AlterField(
            model_name='testgroups',
            name='supergroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='testgroup_supergroup', to='bbconnlab.SuperGroups', verbose_name='Grup super'),
        ),
        migrations.AlterField(
            model_name='testparameters',
            name='decimal_place',
            field=models.IntegerField(default=1, null=True, verbose_name='Tempat desimal'),
        ),
        migrations.AlterField(
            model_name='testparameters',
            name='lastmodification',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah'),
        ),
        migrations.AlterField(
            model_name='testparameters',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh'),
        ),
        migrations.AlterField(
            model_name='testparameters',
            name='method',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Metode'),
        ),
        migrations.AlterField(
            model_name='testparameters',
            name='special_information',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Informasi spesial'),
        ),
        migrations.AlterField(
            model_name='testparameters',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tes unit'),
        ),
        migrations.AlterField(
            model_name='testprices',
            name='dateofcreation',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Dibuat pada'),
        ),
        migrations.AlterField(
            model_name='testprices',
            name='lastmodification',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah'),
        ),
        migrations.AlterField(
            model_name='testprices',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh'),
        ),
        migrations.AlterField(
            model_name='testprices',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bbconnlab.Priority', verbose_name='Prioritas'),
        ),
        migrations.AlterField(
            model_name='testprices',
            name='service',
            field=models.DecimalField(decimal_places=2, help_text='Tarif layanan medis', max_digits=20, verbose_name='Pelayanan medis'),
        ),
        migrations.AlterField(
            model_name='testprices',
            name='tariff',
            field=models.DecimalField(decimal_places=2, help_text='tarif dasar', max_digits=20, verbose_name='tarif'),
        ),
        migrations.AlterField(
            model_name='testprices',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_price', to='bbconnlab.Tests', verbose_name='Tes'),
        ),
        migrations.AlterField(
            model_name='testrefranges',
            name='age_from',
            field=models.IntegerField(blank=True, null=True, verbose_name='Usia dari'),
        ),
        migrations.AlterField(
            model_name='testrefranges',
            name='age_from_type',
            field=models.CharField(blank=True, choices=[('D', 'DAY'), ('M', 'MONTH'), ('Y', 'YEAR')], max_length=3, null=True, verbose_name='Usia dari unit'),
        ),
        migrations.AlterField(
            model_name='testrefranges',
            name='age_to',
            field=models.IntegerField(blank=True, null=True, verbose_name='Usia sampai'),
        ),
        migrations.AlterField(
            model_name='testrefranges',
            name='age_to_type',
            field=models.CharField(blank=True, choices=[('D', 'DAY'), ('M', 'MONTH'), ('Y', 'YEAR')], max_length=3, null=True, verbose_name='Usia sampai unit'),
        ),
        migrations.AlterField(
            model_name='testrefranges',
            name='alfa_value',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nilai alfanumerik'),
        ),
        migrations.AlterField(
            model_name='testrefranges',
            name='any_age',
            field=models.BooleanField(default=True, verbose_name='Semua umur?'),
        ),
        migrations.AlterField(
            model_name='testrefranges',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refranges_gender', to='bbconnlab.Genders', verbose_name='Jenis kelamin'),
        ),
        migrations.AlterField(
            model_name='testrefranges',
            name='lastmodification',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah'),
        ),
        migrations.AlterField(
            model_name='testrefranges',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh'),
        ),
        migrations.AlterField(
            model_name='testrefranges',
            name='lower',
            field=models.IntegerField(blank=True, null=True, verbose_name='Batas bawah'),
        ),
        migrations.AlterField(
            model_name='testrefranges',
            name='operator_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nilai operator'),
        ),
        migrations.AlterField(
            model_name='testrefranges',
            name='special_info',
            field=models.TextField(blank=True, null=True, verbose_name='Informasi spesial'),
        ),
        migrations.AlterField(
            model_name='testrefranges',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refranges_test', to='bbconnlab.Tests', verbose_name='Tes'),
        ),
        migrations.AlterField(
            model_name='testrefranges',
            name='upper',
            field=models.IntegerField(blank=True, null=True, verbose_name='Batas atas'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='can_request',
            field=models.BooleanField(default=True, verbose_name='Dapat di-request'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='dateofcreation',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Dibuat pada'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='ext_code',
            field=models.CharField(max_length=30, verbose_name='Kode eksternal'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='lastmodification',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Nama tes'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='result_type',
            field=models.CharField(choices=[('NUM', 'NUMERIC'), ('ALF', 'ALFANUMERIC'), ('TXT', 'TEXT'), ('IMG', 'IMAGE')], default='NUM', max_length=3, verbose_name='Tipe hasil'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='sort',
            field=models.IntegerField(help_text='Urutan prioritas', verbose_name='Urut'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='specimen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='test_specimen', to='bbconnlab.Specimens', verbose_name='Spesimen'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='test_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='bbconnlab.TestGroups', verbose_name='Grup tes'),
        ),
        migrations.AlterField(
            model_name='worklistorders',
            name='lastmodification',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah'),
        ),
        migrations.AlterField(
            model_name='worklistorders',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh'),
        ),
        migrations.AlterField(
            model_name='worklistorders',
            name='worklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worklist_order', to='bbconnlab.Worklists', verbose_name='Daftar pekerjaan'),
        ),
        migrations.AlterField(
            model_name='worklists',
            name='batch_date',
            field=models.DateField(auto_now_add=True, verbose_name='Tanggal batch'),
        ),
        migrations.AlterField(
            model_name='worklists',
            name='batch_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worklist_batchgroup', to='bbconnlab.BatchGroups', verbose_name='Grup batch'),
        ),
        migrations.AlterField(
            model_name='worklists',
            name='lastmodification',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah'),
        ),
        migrations.AlterField(
            model_name='worklists',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh'),
        ),
        migrations.AlterField(
            model_name='worklisttests',
            name='lastmodification',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah'),
        ),
        migrations.AlterField(
            model_name='worklisttests',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh'),
        ),
        migrations.AlterField(
            model_name='worklisttests',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worklisttest_test', to='bbconnlab.Tests', verbose_name='Tes'),
        ),
        migrations.AlterField(
            model_name='worklisttests',
            name='worklistorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worklisttest_worklistorder', to='bbconnlab.WorklistOrders', verbose_name='Daftar pekerjaan order'),
        ),
    ]
