# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-02 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbconnlab', '0004_auto_20181101_2149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workareatestgroups',
            options={'ordering': ['sort'], 'permissions': (('view_workareatestgroups', 'Can view workareatestgroups'),), 'verbose_name': 'Workareatestgroup', 'verbose_name_plural': 'Workareatestgroups'},
        ),
        migrations.RemoveField(
            model_name='workareatestgroups',
            name='woarkarea',
        ),
        migrations.AddField(
            model_name='workarea',
            name='sort',
            field=models.IntegerField(default=1, help_text='Urutan prioritas', verbose_name='Urut'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workareatestgroups',
            name='testgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workareatestgroup_testgroup', to='bbconnlab.TestGroups', verbose_name='Testgroup'),
        ),
        migrations.AddField(
            model_name='workareatestgroups',
            name='workarea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workareatestgroup_workarea', to='bbconnlab.Workarea', verbose_name='Area kerja'),
        ),
    ]
