# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-04 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbconnlab', '0005_auto_20181101_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workareatestgroups',
            old_name='woarkarea',
            new_name='workarea',
        ),
    ]
