# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbconnlab', '0005_auto_20180719_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testprices',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbconnlab.Priority', verbose_name='Prioritas'),
        ),
        migrations.AlterField(
            model_name='testprices',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_price', to='bbconnlab.Tests', verbose_name='Tes'),
        ),
    ]
