# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 16:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bbconnlab', '0008_auto_20180721_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDiagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateofcreation', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_diagnosis', to='bbconnlab.Diagnosis', verbose_name='Diagnosa')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_diagitems', to='bbconnlab.Orders', verbose_name='Order')),
            ],
            options={
                'ordering': ['order', 'diagnosis'],
                'verbose_name': 'Order diagnosis',
                'verbose_name_plural': 'Order diagnosis',
                'permissions': (('view_ordertests', 'Can view order tests'),),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Service Name')),
                ('ext_code', models.CharField(max_length=30, verbose_name='Kode eksternal')),
                ('lastmodification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Terakhir diubah')),
                ('lastmodifiedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bbconnlab.Service', verbose_name='Service'),
        ),
    ]
